[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

# Configuração de redirecionamentos
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Configuração de headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; connect-src 'self' https://www.google-analytics.com; frame-src 'self' https://www.google.com;"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Configuração para arquivos de mídia
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.otf"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuração para arquivos HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Configurações de segurança
[build.processing]
  skip_processing = false

# Configuração de segurança para varreduras de segredos
[context.production]
  command = "npm run build:production"
  [context.production.environment]
    NODE_ENV = "production"
    SECRETS_SCAN_ENABLED = "true"
    SECRETS_SCAN_OMIT_PATHS = "node_modules/**,.netlify/**,.git/**,.github/**,.vscode/**,.husky/**,*.log,*.lock,package-lock.json,yarn.lock,.env.example,README.md,CONTRIBUTING.md"
    SECRETS_SCAN_OMIT_KEYS = "NODE_ENV,PORT,LOG_LEVEL,LOG_FORMAT,EMAIL_SERVICE,ALLOWED_ORIGINS,ALLOWED_METHODS,ALLOWED_HEADERS"

# Configuração para branches de desenvolvimento
[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    SECRETS_SCAN_ENABLED = "false"

# Configuração para branches de feature
[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    SECRETS_SCAN_ENABLED = "false"

# Configuração para ambiente de desenvolvimento local
[dev]
  command = "npm run dev"
  targetPort = 3000
  publish = "dist"
  autoLaunch = false
  framework = "#custom"

# Configuração de build específica para o Netlify
[build.lifecycle]
  preBuild = "npm install"
  postBuild = "npm run postbuild"

# Configuração de funções serverless (se aplicável)
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
